version: '3'
services:
  flask:
    build:
      context: ht_flask
      dockerfile: Dockerfile
    container_name: flask
    image: digitalocean.com/flask-python:3.6
    restart: unless-stopped
    environment:
      APP_PORT: 5000
      MONGO_DATABASE: ht_db
      MONGODB_HOSTNAME: mongodb
    volumes:
      - ./ht_flask/:/flask_app
    depends_on:
      - mongodb
    ports:
      - 5000:5000
    networks:
      - frontend
      - backend

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod
    environment:
      MONGO_INITDB_DATABASE: ht_db
      MONGO_DATA_DIR: /data/db

    volumes:
      - mongodbdata:/data/db
    networks:
      - backend


networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local


